import { faHeartBroken, faSearch, faChevronDown, faChevronUp, faUser, faBook, faEdit, faHeart, faUserShield, faSignOutAlt, faSignInAlt, faInfoCircle, faLock, faArrowDown, faArrowUp, faChevronCircleLeft, faChevronCircleRight, faStar, faPlus, faClock, faUsers, faWeight, faCheck, faTimes } from '@fortawesome/free-solid-svg-icons';

export const Icons = {
	faSearch,
	faChevronDown,
	faChevronUp,
	faClock,
	faCheck,
	faUser,
	faUsers,
	faBook,
	faEdit,
	faHeart,
	faUserShield,
	faHeartBroken,
	faSignOutAlt,
	faSignInAlt,
	faInfoCircle,
	faLock,
	faArrowDown,
	faArrowUp,
	faChevronCircleLeft,
	faChevronCircleRight,
	faStar,
	faTimes,
	faPlus,
	faWeight,
};